# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a6e7cb03af9d5ef9cc2e2eea975a5c3df890443fefe166fb91bfed0d81f5a684d7e7ad29729d7cf546739e7aad08e971b4f15ad513265bd942fd1f34151c357

test:
  secret_key_base: ccd31675a3bfbfcff6130ad9e80cc979bb247c07ca45535bd47044cdcf4cd946861d874c244fee784f3623005532da1e26925caf5b21b5630546b47b24f8edc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
